project_id = "loamacrszlgxhaqvnkzw"

[functions.incoming-message]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-satisfaction-survey]
verify_jwt = false

[functions.chatbot-process]
verify_jwt = false

[functions.evolution-api]
verify_jwt = false

[functions.ai-chat-assist]
verify_jwt = false

[functions.ai-report-gen]
verify_jwt = false

[functions.ai-annotation]
verify_jwt = false
